import { Link } from 'react-router-dom';

const Sidebar = () => {
    return (
        <div className='w-1/3 h-screen overflow-scroll border-white border'>
            <h1>Songlist</h1>
            <ul>
                {Object.entries(music_list).map(([key, value]) => (
                    <li key={key}>
                        <Link to={`music/${key}`}>{value}</Link>
                    </li>
                ))}
            </ul>
        </div>
    );
};

export default Sidebar;

type MusicList = {
    [key: string]: string;
};

export const music_list: MusicList = {
    A8UaAoNKI6k: 'Back At One',
    p0BiGek2bKA: 'Since U Been Gone',
    gt_12Y6hPLc: 'Dancing in the Moonlight (2001 Remix)',
    KVbeMWAPWmc: 'I Still Believe',
    biwsNfnamYw: 'I Just Wanna Live',
    VOiZC020nl0: 'Caribbean Queen (No More Love On the Run)',
    iId8bASZy8s: 'Everybody Get Up (Radio Mix)',
    WQnAxOQxQIU: 'Savage Garden - Truly Madly Deeply',
    '3OMaHIZlP0Y': '[You Drive Me] Crazy',
    Bid6LmRU1d8: 'Blame It on the Boogie',
    kU0P2P5dtjE: 'The Show',
    'RUWAFhwrN-I': 'Leave (Get Out)',
    'gyt14K0-Pjg': 'Blue - Best In Me',
    '27zOar_iEOA': 'Hysteria',
    '7wBgcalM4c4': 'Time After Time',
    LvyHVgocP_0: 'Ocean Avenue',
    '0yBnIUX0QAE': 'Toploader - Dancing in the Moonlight (Official Video)',
    yz4me7Vwr1w: 'Genie In a Bottle',
    S8WBZLGoSGs: 'Bella Luna',
    CJ5J7MxEexo: 'Angel',
    gGdGFtwCNBE: 'The Killers - Mr. Brightside (Official Music Video)',
    xFrGuyw1V8s: 'Abba - Dancing Queen (Official Music Video Remastered)',
    '-qCDypgAV_E': 'Jessica Simpson - Irresistible',
    '1jbp5mb6AUU': 'Best Part (feat. H.E.R.)',
    A_iTphwVNYs: 'Waterfalls',
    WUhg7pVDhPY: 'Pop Princess',
    eEpbE2UJXcU: 'Face Down',
    OR4ooJWgG0A: 'Stranger By The Day',
    '5qZQEq_C3vc': 'Numb',
    'RH-dnsXgaIM': 'My Friends Over You',
    oE56g61mW44: "Isn't She Lovely",
    KWLGyeg74es: 'Fireflies',
    kLtdJ1rM8es: 'The Anthem',
    fbee7OkeVjg: 'Viva Forever',
    gelwwYuYGn0: 'Just the Two of Us',
    kkB4qTpRx_E: 'Always Be My Baby',
    BfRBYmRrhYg: 'Time is Running Out',
    AC4ICSAKhQo: 'Only When I Sleep',
    'weKV-CzcHhg': 'The Chronicles of Life and Death',
    DTtb9rt1tnk: 'Complicated',
    'PJ-qGM2Sh_I': 'I Just Called To Say I Love You',
    'js-Wg53U-3k': 'Radio',
    LafroQ7wip4: 'I Know What You Want',
    leQjqIE39vQ: 'Uptown Girl (Radio Edit)',
    XleOkGsYgO8: 'The All-American Rejects - Move Along (Official Music Video)',
    adNzZIBdXss: 'A Little Too Not Over You',
    q927IdzxCo4: 'Michelle Branch - Are You Happy Now [Official Music Video]',
    oG08ukJPtR8:
        'Michael Jackson, Justin Timberlake - Love Never Felt So Good (Official Video)',
    nFCuyLwhUzM: 'Kelly Clarkson - Walk Away',
    C6MOKXm8x50: 'Fall Out Boy - Dance, Dance (Official Music Video)',
    lkzXi4cmdJk: 'Kiss from a Rose',
    Yg9KJW2Zi3c: 'We Belong Together',
    MX5DhzuwLfc: 'Step On Me',
    z__BOLWspMI: "I'm All About You",
    r2QyLA5w3ps: 'Breakaway',
    '6Z28t-kfU5A': 'Irresistible',
    wRkDsxDf7c4: 'Show You the Way to Go',
    oBIxScJ5rlY: 'John Mayer - Waiting On the World to Change (Official Video)',
    DQ514qIthSc: 'Down',
    '_4-0dnvknOY': 'Butterfly',
    'vc6vs-l5dkc':
        'Panic! At The Disco: I Write Sins Not Tragedies [OFFICIAL VIDEO]',
    GLFp_C0Zi3M: 'I Don\'t Want to Miss a Thing (From "Armageddon" Soundtrack)',
    OzRdHojqKn8: 'Live High',
    CbuLnJqUFLQ: 'Sometimes',
    CzmvCEL1ilI: 'Catch Your Wave',
    YA1TpXk1y3c: "Say You'll Be There",
    ziip1oB52vo: 'Insomnia',
    qSIOp_K5GMw: 'Brandy & Monica - The Boy Is Mine (Official Video)',
    '5YVU42Vow5U': 'This I Promise You',
    'Uk0zv8r-wRw': 'Invisible',
    B0A3gitDngI: 'Every Morning (Remastered)',
    '1350czEuKzg': 'The Click Five - Jenny (Official Video)',
    Kv2x8HxZ9cA: 'All the Love in the World',
    jtePSuQB5S0: "I Don't Wanna Be In Love (Dance Floor Anthem)",
    x_dtKRzbCTU: 'Mr. Jones',
    kW3aMKTrPZg: 'Runaway',
    Efa6BAWPm9o: 'Losing My Religion',
    MpDM6ygsb20: 'Part-Time Lover',
    'y-STe_g795o': 'Fall In Love Alone',
    psuRGfAaju4: 'Owl City - Fireflies (Official Music Video)',
    virQa6KHPNE: 'Every Morning',
    caJxSovqA44: 'Pieces Of Me',
    desJKYvdq9A: 'Good Charlotte - The Anthem (Official Video)',
    qYxGmzVbvkc: 'Just Once (New Version)',
    w7aIZ6X3IHg: 'Those Sweet Words',
    gFP0m8pRtRs: 'Beautiful Soul',
    nXB4xBnP22o: 'Change the World',
    '2BXRpq3MEGY': 'Vanilla Twilight',
    CczcMarUoVk: "Don't Stop Me Now (Remastered 2011)",
    OjETibEMbJY:
        'Kylie Minogue - In Your Eyes (Official Video) [Full HD Remastered]',
    '-r85WmKI9Uo': 'Because Of You',
    _e7bqZGPyFI: 'Breaking the Habit',
    AqQuRw0S6b4: 'This Love',
    'oKOtzIo-uYw': 'Fugees - Killing Me Softly With His Song (Official Video)',
    qOr2QVjsQBM: 'Walking Away',
    xKyGyXlHS9Y: 'Ashlee Simpson - Boyfriend',
    vKwowKeEv5w: 'My Love',
    'U9-f4Mosb_A': 'Sunday Morning',
    '7kxQaZFXIxs': 'Jessica Simpson - Come on Over',
    LHBbWBX_azA: 'She Will Be Loved',
    v_uncMEJkBc: 'Welcome to the Black Parade',
    IDCFX5NShlE: 'Never Say Goodbye',
    UOf6uHwB3Tk: 'Lost Stars',
    BLZWkjBXfN8: 'In the End',
    BprKN1ffH3k: 'Stronger',
    adLGHcj_fmA:
        'Bruno Mars, Anderson .Paak, Silk Sonic - Leave the Door Open [Official Video]',
    N4g4502eGfk: 'Virtual Insanity',
    '6VY8ZxcDh1s': 'Without You',
    t9lJcKoMI2g: 'Graduation (Friends Forever)',
    '1fk45t42yPE': 'Chasing the Sun',
    j65_xyAlkns: 'Crush',
    BPevXhntUvI: 'Your Body Is a Wonderland',
    'lnl9U-hHp1I': 'It Must Have Been Love (From the Film "Pretty Woman")',
    HAlZDUouniI: 'Something Stupid (feat. Reese Witherspoon)',
    RibtqL3Y0Cg: 'What Can I Do',
    '-YQ8IbVIwPM': 'Somewhere I Belong',
    'd8ok2P-t5yo': 'Unbelievable (Radio Edit)',
    '5HsztKF4-yg': 'With You',
    UYocLBXr7hQ: 'Sk8er Boi',
    'Dbb7xeZGR-U': 'Craig David - Walking Away (Official Video)',
    'f8qorD-zBZs': "If You're Not The One",
    fzU2FOEOK1E: "Don't Love You No More (I'm Sorry)",
    '95-2BKDQ6jQ': 'Irresistible',
    mGrufrND1m0: 'Lifestyles of the Rich & Famous',
    eLbmdG8U60E: 'As',
    DHPZpSYSpR4: 'Good Day',
    I_izvAbhExY: "Bee Gees - Stayin' Alive (Official Video)",
    '2fDzCWNS3ig': 'The Weeknd - Out of Time (Official Video)',
    pU2ukeS2JTE: 'Craig David - Rise & Fall ft. Sting (Official Video)',
    '2rXJgpu0RlA': 'Real to Me (Edit)',
    gPDcwjJ8pLg:
        'The All-American Rejects - Dirty Little Secret (Official Music Video)',
    IKpNL2Nm9SM: 'The Way You Look Tonight',
    '0Cawb8dj2s8': 'I Lay My Love on You (Remix)',
    '84J_XmGkX48': 'Papercut',
    Qe2pjBYskUU: 'So Yesterday',
    UyMvBWVGaOA: 'Every Summertime',
    JvtzWusWvc8: 'Too Little Too Late',
    'Oextk-If8HQ': 'Keane - Somewhere Only We Know (Official Music Video)',
    v6nR6zzn9E8: 'The Prince Of Egypt (When You Believe)',
    iGbPR36zGx4: 'Wherever You Will Go',
    rYHk2D3Xlqs: 'True',
    '3ZdbHUolTi8': 'My All',
    Hw_c6dDFP1c: 'Addicted',
    '3F3vjO8UY2E': 'Listen To Your Heart',
    bFF700kkTeo: 'NIKI - Every Summertime (Living Room Version)',
    'GEo7W-uJNkc': 'Accidentally In Love (From "Shrek 2" Soundtrack)',
    kry7NkELYYE: 'Can You Stand The Rain',
    xAbhq4uguSM: 'Prettiest Friend - Jason Mraz [Lyrics]',
    J1iIr5FeWHo: 'With You',
    '1rx8jq3QivI': 'Sunday Morning (Acoustic)',
    BKtrWU4zaaI: "Des'ree - Life (Official Video)",
    DGnXL4pvdBg: 'Hero',
    rjOhZZyn30k: 'Corinne Bailey Rae - Put Your Records On',
    'cpB34q-hlvg': "It's a Beautiful Day",
    A93OQy81TYs: "I'm Yours",
    DXvMT_mVbqw: 'K-Ci & JoJo - All My Life (Official Music Video)',
    pnUEiEW8lmc: 'The Calling - Adrienne',
    n9DmdAwUbxc: "What You Won't Do for Love",
    '0fhSOAf6yzM': 'Trouble Is a Friend (Spike Stent Remix)',
    '-5qqrMu_AZc': "Gangsta's Paradise",
    Lnq5Az8aLpA: "That's What Friends Are For",
    f1De87ETXwo: "Nothing's Gonna Change My Love for You",
    taDnpGb5I4k: 'A Little Bit',
    '-5XQSMrTQt4': 'Heart of Mine',
    A__cH65WRvE: 'Californication',
    SPUJIbXN0WY: 'Michael Bublé - Everything [Official Music Video]',
    yXm1oCKLOFI: 'Just the Girl',
    mom2TLs3Fi0: 'Smooth',
    N2ICtCO8TCw: 'Take That - Back for Good (Official Video)',
    jKajgKJn948: 'L O V E',
    '8901V1M5lDk': 'Otherside',
    F1A5LvxVuL8: 'Spinning Around',
    beINamVRGy4:
        'Third Eye Blind - Semi-Charmed Life (Official Music Video) [HD]',
    SC5zbR2E3Vs: 'Welcome to My Life',
    jc6CNwlATdc: 'Summer Sunshine',
    aTso2qhq5NA: 'Make It Mine',
    '2KeFjLDkOrI': 'Fly Away',
    fhnfcHSPrfw: "I'll Be There For You",
    RuPr33Jk2A4: 'Where Is The Love?',
    Qgd_TRKSWa8: 'Show Me the Meaning of Being Lonely',
    '-rQbZsorrxs': 'Crush',
    '7kDUn5vescA': 'Stuck',
    VWl7WjAtBME: 'Jessica Simpson - With You',
    rj5wZqReXQE: 'Wonderwall (Remastered)',
    '91Niv2q4gvc': '... Baby One More Time',
    I6NU3kWqnDE: 'Crawling',
    HrqvMnYv9z8: 'Ashlee Simpson - Shadow (Official Video)',
    vrKeDnVwC8Y: 'Picture Of You',
    roPQ_M3yJTA: "Nelly Furtado - I'm Like A Bird (Official Music Video)",
    qQ0zxuWFxrY: 'The Reason',
    OBo2S_IWjKM: 'Details in the Fabric (feat. James Morrison)',
    fHbmVbh449s: 'Shut Up!',
    '4jeCvAccUMk': "That's the Way It Is",
    NI6aOFI7hms: 'The Cardigans - Lovefool (Official Music Video)',
    z2Y_2mhFp5g: 'Breathless',
    Ciz7FJ_ifZU: 'Sweet Baby',
    NkVsJGl5d6E: 'Mandy Moore - Candy (Video)',
    cL4uhaQ58Rk: 'Adam Levine - Lost Stars (from Begin Again)',
    FDdkpmSNo4U: 'Santeria',
    vAZA6oNEWZg: 'Shake Your Body (Down to the Ground)',
    bUjXNeN1bYY: 'If You Come Back',
    BYjwjK7Q7cc: 'When The Lights Go Out (US Remix)',
    LZxKYsCijVY: 'The Tide Is High (Radio Mix)',
    '67CN8FOCc84': 'Dancing in the Moonlight',
    ltjio4AM2uw: "Let's Groove",
    'N-_mHedypEU': 'Supermassive Black Hole',
};
